import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
    createYandexMetricaScript,
    YandexMetricaInit,
    YandexMetricaNoscript,
    YandexMetricaProvider,
} from "@yandex-metrica/react";
import Script from "next/script";
import { Header } from "./header";
import { MetricaRouteTracking } from "./route-tracking";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-zinc-50`}>
                <YandexMetricaProvider enabled debug>
                    <Script id="yandex-metrica">{createYandexMetricaScript()}</Script>
                    <YandexMetricaInit
                        clientID={process.env.NEXT_PUBLIC_YANDEX_METRICA_ID!}
                        initParameters={{ defer: true, clickmap: true, ecommerce: true }}
                    />
                    <YandexMetricaNoscript />
                    <MetricaRouteTracking />
                    <Header />
                    {children}
                </YandexMetricaProvider>
            </body>
        </html>
    );
}
